event-manager/mydjango/graphqlendpoint/urls.py
from django.conf.urls import url
from graphqlendpoint.views import log_in, log_out, user_list, sign_up

app_name="eventsmanager"

urlpatterns = [
    url(r'^sign_up/$', sign_up, name='sign_up'),
    url(r'^log_in/$', log_in, name='log_in'),
    url(r'^log_out/$', log_out, name='log_out'),
    url(r'^$', user_list, name='user_list'),
]

event-manager/mydjango/mydjango/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from graphene_django.views import GraphQLView
from mydjango.schema import schema

from django.views.decorators.csrf import csrf_exempt



urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^graphql', csrf_exempt(GraphQLView.as_view(graphiql=True, schema=schema))),
    
]

event-manager/mydjango/graphqlendpoint/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User
# Create your models here.


class LoggedInUser(models.Model):
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL, related_name='logged_in_user', on_delete=models.CASCADE)


class Category(models.Model):
    title = models.CharField(max_length=200, null=True)
    predecessor = models.CharField(max_length=200,null=True, blank=True)
    searchcode = models.CharField(max_length=200, null=True)
    ot_id = models.CharField(max_length=200, unique=True, null=True)

    def create_from_json(self, data):
        self.title = data.get("Title")
        self.searchcode = data.get("SearchCode")
        self.ot_id = data.get("id")

    def __str__(self):
        return "%s" % self.title


class Call(models.Model):
    ucid = models.CharField(max_length=200, unique=True)
    state = models.CharField(max_length=200, null=True, default="new")
    origin = models.CharField(max_length=200, null=True)
    destination = models.CharField(max_length=200, null=True)
    call_type = models.CharField(max_length=200, null=True)
    start = models.DateTimeField(max_length=200, null=True)
    end = models.DateTimeField(max_length=200, null=True, blank=True)
    isContactCenterCall = models.BooleanField(default=False)
    history = models.CharField(max_length=600, null=True)

    def __str__(self):
        return "%s" % self.ucid

    def getTransfers(self):
        tf = Transfer.objects.filter(call=self).order_by('ttimestamp')
        return tf
    

    def updatehistory(self):
        self.history = ""
        for t in self.getTransfers():
            if t.torigin == "" and t.torigin:
                # first transfer
                self.history == t.tdestination
            else:
                # other transfers
                self.history = "%s -> %s" % (self.history, t.tdestination)
        self.save()


class Agent(models.Model):
    firstname = models.CharField(max_length=30, null=True, blank=True)
    lastname = models.CharField(max_length=30, null=True, blank=True)
    active = models.BooleanField(default=True)
    ot_userloginname = models.CharField(max_length=30, null=True, blank=True)
    ot_userdisplayname = models.CharField(
        max_length=100, null=True, blank=True)
    ot_id = models.CharField(max_length=30, null=True, blank=True)
    user = models.OneToOneField(
        User, on_delete=models.SET_NULL, null=True, blank=True)
    phone_login = models.CharField(max_length=3, null=True, blank=True)
    phone_active = models.BooleanField(default=False)
    ext = models.CharField(max_length=3, null=True, unique=True)
    phone_state = models.CharField(
        max_length=30, default="available", blank=True)
    email = models.CharField(max_length=35, null=True)
    avatar = models.ImageField(upload_to='userimage', blank=True)
    current_call = models.ForeignKey(
        Call, null=True, on_delete=models.SET_NULL, related_name='current_agent', blank=True)
    isQueueLine = models.BooleanField(default=False)
    
    def __str__(self):
        return "%s" % self.ext


class Ticket(models.Model):
    creationdate = models.DateTimeField(null=True)
    title = models.CharField(max_length=200, null=True)
    category = models.ForeignKey(
        Category, related_name='category_tickets', on_delete=models.DO_NOTHING, null=True)
    applicant = models.ForeignKey(
        Agent, related_name='tickets_created', on_delete=models.CASCADE, null=True)
    responsible = models.ForeignKey(
        Agent, related_name='tickets_responsible', on_delete=models.CASCADE, null=True)
    state = models.CharField(max_length=200, null=True)
    solution = models.TextField(null=True, default="")
    description = models.TextField(null=True, default="")
    ot_id = models.CharField(max_length=200, null=True)

    def __str__(self):
        return "%s" % self.title


class Event(models.Model):
    creationdate = models.DateTimeField(null=True)
    end = models.DateTimeField(null=True, blank=True)
    ot_id = models.IntegerField(null=True, blank=True)
    applicant = models.ForeignKey(
        Agent, related_name='events_applicant', on_delete=models.CASCADE, null=True, blank=True)
    responsible = models.ForeignKey(
        Agent, related_name='events_responsible', on_delete=models.CASCADE, null=True, blank=True)
    state = models.CharField(max_length=200, default="new", null=True, blank=True)
    transferhistory = models.CharField(max_length=200, null=True, blank=True)
    phone = models.CharField(max_length=200, null=True, blank=True)
    ticket = models.ForeignKey(
        Ticket, related_name='tickets', on_delete=models.CASCADE, null=True, blank=True)
    call = models.ForeignKey(
        Call, on_delete=models.SET_NULL, null=True, related_name='event', blank=True)

    def __str__(self):
        return "%s" % self.ot_id


class Transfer(models.Model):
    torigin = models.CharField(max_length=200, null=True)
    tdestination = models.CharField(max_length=200)
    ttimestamp = models.DateTimeField(max_length=200)
    call = models.ForeignKey(Call, on_delete=models.CASCADE)


class ActiveCalls(models.Model):
    call = models.OneToOneField(
        Call, related_name='active', on_delete=models.CASCADE)

event-manager/mydjango/graphqlendpoint/views.py
from django.contrib.auth import login, logout
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.urls import reverse
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model, login, logout
User = get_user_model()
from graphqlendpoint.models import Call

def log_in(request):
    form = AuthenticationForm()
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            login(request, form.get_user())
            return redirect(reverse('eventsmanager:user_list'))
        else:
            print(form.errors)
    return render(request, 'eventsmanager/log_in.html', {'form': form})

@login_required(login_url='/log_in/')
def log_out(request):
    logout(request)
    return redirect(reverse('eventsmanager:log_in'))

def sign_up(request):
    form = UserCreationForm()
    if request.method == 'POST':
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            form.save()
            return redirect(reverse('eventsmanager:log_in'))
        else:
            print(form.errors)
    return render(request, 'eventsmanager/sign_up.html', {'form': form})

@login_required(login_url='/log_in/')
def user_list(request):
    users = User.objects.select_related('logged_in_user')
    for user in users:
        user.status = 'Online' if hasattr(user, 'logged_in_user') else 'Offline'
    return render(request, 'eventsmanager/user_list.html', {'users': users})


@login_required(login_url='/log_in/')
def user_list(request):
    calls = Call.objects.select_related('active')
    calls_list = []
    for call in calls:
        if hasattr(call, 'active'):
            calls_list.append(call)
    return render(request, 'eventsmanager/call_list.html', {'calls': calls_list}) 

event-manager/mydjango/graphqlendpoint/templates/eventsmanager/_base.html
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
  <title>Example Channels</title>
</head>
<body>
  <div class="container">
    <br>
    {% block content %}{% endblock content %}
  </div>
  <script src="//code.jquery.com/jquery-3.1.1.min.js"></script>
  {% block script %}{% endblock script %}
</body>
</html>

event-manager/mydjango/graphqlendpoint/templates/eventsmanager/call_list.html
{% extends 'eventsmanager/_base.html' %}

{% block content %}
  <a href="{% url 'eventsmanager:log_out' %}">Log out</a>
  <br>
  <ul>
     <li id='data'></li>
    {% for call in calls %}
      <!-- NOTE: We escape HTML to prevent XSS attacks. -->
      <li data-call="{{ call.ucid|escape }}">
        {{ call.ucid|escape }}: {{ call.state|default:'Offline' }}
      </li>
     
    {% endfor %}
  </ul>
{% endblock content %}

{% block script %}
  <script>
    var socket = new WebSocket('ws://' + window.location.host + '/calls/');

    socket.onopen = function open() {
      console.log('WebSockets connection created.');
    };

    socket.onmessage = function message(event) {
      var data = JSON.parse(event.data);
      // NOTE: We escape JavaScript to prevent XSS attacks.
      var ucid = encodeURI(data['ucid']);
      var user = $('#call');


      
      user.html(ucid + ': Online');
     }
    if (socket.readyState == WebSocket.OPEN) {
      socket.onopen();
    }
  </script>
{% endblock script %}

event-manager/mydjango/graphqlendpoint/templates/eventsmanager/log_in.html
{% extends 'eventsmanager/_base.html' %}

{% block content %}
  <form action="{% url 'eventsmanager:log_in' %}" method="post">
    {% csrf_token %}
    {% for field in form %}
      <div>
        {{ field.label_tag }}
        {{ field }}
      </div>
    {% endfor %}
    <button type="submit">Log in</button>
  </form>
  <p>Don't have an account? <a href="{% url 'eventsmanager:sign_up' %}">Sign up!</a></p>
{% endblock content %}

event-manager/mydjango/graphqlendpoint/templates/eventsmanager/sign_up.html
{% extends 'eventsmanager/_base.html' %}

{% block content %}
  <form action="{% url 'eventsmanager:sign_up' %}" method="post">
    {% csrf_token %}
    {% for field in form %}
      <div>
        {{ field.label_tag }}
        {{ field }}
      </div>
    {% endfor %}
    <button type="submit">Sign up</button>
    <p>Already have an account? <a href="{% url 'eventsmanager:log_in' %}">Log in!</a></p>
  </form>
{% endblock content %}

event-manager/mydjango/graphqlendpoint/templates/eventsmanager/user_list.html
{% extends 'eventsmanager/_base.html' %}

{% block content %}
  <a href="{% url 'eventsmanager:log_out' %}">Log out</a>
  <br>
  <ul>
    {% for user in users %}
      <!-- NOTE: We escape HTML to prevent XSS attacks. -->
      <li data-username="{{ user.username|escape }}">
        {{ user.username|escape }}: {{ user.status|default:'Offline' }}
      </li>
    {% endfor %}
  </ul>
{% endblock content %}

{% block script %}
  <script>
    var socket = new WebSocket('ws://' + window.location.host + '/users/');

    socket.onopen = function open() {
      console.log('WebSockets connection created.');
    };

    socket.onmessage = function message(event) {
      var data = JSON.parse(event.data);
      // NOTE: We escape JavaScript to prevent XSS attacks.
      var username = encodeURI(data['username']);
      var user = $('li').filter(function () {
        return $(this).data('username') == username;
      });

      if (data['is_logged_in']) {
        user.html(username + ': Online');
      }
      else {
        user.html(username + ': Offline');
      }
    };

    if (socket.readyState == WebSocket.OPEN) {
      socket.onopen();
    }
  </script>
{% endblock script %}